### ISSUE TITLE
Translation Request: Russian

### ISSUE THREAD

**Issue by Cheewbacca** [denysdovhan/wtfjs#181] opened 2021-01-31 21:39 UTC
I am able to translate this language [yes/no] 
I can try to do my best and help with translation, however my English isn't good enough

**Comment by nurlansu** [comment] 2021-02-03 17:20
Duplicate of https://github.com/denysdovhan/wtfjs/issues/134.

**Comment by denysdovhan** [comment] 2021-02-04 16:11
Duplicate of #134

**Closed by denysdovhan** 2021-02-04 16:11 UTC
Labels: duplicate, translation
