### ISSUE TITLE
No need for semicolon 

### ISSUE THREAD

**Issue by sdwvit** [denysdovhan/wtfjs#77] opened 2018-01-30 20:51 UTC
Nice example of interpretator stupidness 👯 (taken from http://lurkmore.to/Javascript )

function foo(){}
foo()
[1,2,3].map(console.log.bind(console))  // Uncaught TypeError: undefined is not an object

however this works:
function foo(){}
foo()
;[1,2,3].map(console.log.bind(console))

**Comment by denysdovhan** [comment] 2021-02-05 12:39
Looks like a duplicate of this example: https://github.com/denysdovhan/wtfjs#tricky-return

That's why I close this. Thanks for reporting!

**Closed by denysdovhan** 2021-02-05 12:39 UTC
Labels: proposal
